### ISSUE TITLE
Python 3 not found even tho it is instaleld and  in Path 

### ISSUE THREAD

**Issue by daslicht** [corpnewt/SSDTTime#14]
Hi,
even tho python 3 is instaleld I get the following message, any idea, please?
![](https://i.imgur.com/JlQYFHS.png)

**Comment by whiteforcekali16** [comment]
Hello, just curious what version of Python 3 is needed for this program to run?
I'm on Windows 7, and installed 3.2.3 (which seems to be only one i can install on Win7).
Error:
Traceback (most recent call last):
  File "C:\Users\admin\Documents\MacOS USB\SSDTTime-master\SSDTTime.py", line 1, in <module>
    from Scripts import *
  File "C:\Users\admin\Documents\MacOS USB\SSDTTime-master\Scripts\dsdt.py", line 2, in <module>
    from . import run, downloader, utils
  File "C:\Users\admin\Documents\MacOS USB\SSDTTime-master\Scripts\utils.py", line 179
    reset = u"\u001b[0m"
                       ^
SyntaxError: invalid syntax

Script exited with error code: 1

Press [enter] to exit...

**Comment by corpnewt** [comment]
Looks like python.org suggests that python 3.8.x should run on Windows 7 as their warnings about compatibility only start with 3.9.x:
![image](https://user-images.githubusercontent.com/12772521/159567468-b047b771-4c07-4a8a-b833-8e600e930447.png)

Python 3.8.11 and newer appear to be security fixes, and do not come with installers - but you could try [3.8.10](https://www.python.org/downloads/release/python-3810/) and see.

I tried installing 3.2.3 and running the script (fixing errors as they pop up), but it seems like an uphill battle.  You can also try installing a Python 2 version, as all my scripts (excluding my discord bot) work with py2/py3.

-CorpNewt
