### ISSUE TITLE
AN ERROR OCCURRED

### ISSUE THREAD

**Issue by Drahrekot** [corpnewt/SSDTTime#53]
After I ran the python file and ran into an error

`Press [enter] to continue...
An error occurred: 'SSDT' object has no attribute 'w'
Press [enter] to continue...^CTraceback (most recent call last):
  File "/home/kiriya/Downloads/SSDTTime-master/SSDTTime.py", line 1238, in <module>
    s.main()
  File "/home/kiriya/Downloads/SSDTTime-master/SSDTTime.py", line 1182, in main
    self.u.resize(self.w,self.h)
AttributeError: 'SSDT' object has no attribute 'w'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kiriya/Downloads/SSDTTime-master/SSDTTime.py", line 1241, in <module>
    input("Press [enter] to continue...")
KeyboardInterrupt
`

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/SSDTTime/commit/d9caab1f19d185e9ffb0dca04383a7e14c358c33).

-CorpNewt
